name: Release Client Lib

on:
  workflow_dispatch:
  push:
    tags:
      - 'geobroker-client-lib-*'

jobs:
  build_maven_artifacts:
    name: Build Maven Artifacts
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'geobroker-client-lib-') }}
    permissions:
      packages: write
      contents: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Build Maven Project
        run: mvn clean install deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          body: 'Auto-generated release - release notes tba'
